Repository team-vaco-20/ssakssak-commit, pull requests merged in 2025-08, with the labels that each got.

#5 Feat: 보일러 플레이팅
  .gitignore
  .husky/pre-commit
  README.md
  components.json
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  prettier.config.cjs
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/ui/common/badge.tsx
  src/app/ui/common/button.tsx
  src/app/ui/common/combobox.tsx
  src/app/ui/common/command.tsx
  src/app/ui/common/dialog.tsx
  src/app/ui/common/input.tsx
  src/app/ui/common/pagination.tsx
  src/app/ui/common/popover.tsx
  src/app/ui/common/select.tsx
  src/app/ui/common/table.tsx
  src/app/ui/common/textarea.tsx
  src/lib/logger.ts
  src/lib/utils.ts
  src/stores/useStore.ts
  tsconfig.json
Labels: 🏗️ build, ✨ feat, 📦 chore

#14 Feat: 메인 페이지 초기 기능 구현
  package-lock.json
  package.json
  src/app/api/branches/route.ts
  src/app/types/branch.ts
  src/app/types/error-args.ts
  src/constants/error-messages.ts
  src/constants/github-api.ts
  src/constants/validations.ts
  src/errors/app-error.ts
  src/errors/bad-request-error.ts
  src/errors/not-found-error.ts
  src/infra/github-api/github.ts
  src/lib/parse-repository-url.ts
  src/lib/validators/generate-error-message.ts
  src/lib/validators/repository-url.ts
  src/services/branch/branch.ts
Labels: 📝 docs, ✨ feat, 🔍 review

#12 Feat: 메인 페이지 UI 작업
  package-lock.json
  package.json
  src/app/page.tsx
  src/app/ui/common/combobox.tsx
  src/app/ui/common/error-message.tsx
  src/app/ui/common/header.tsx
  src/app/ui/common/input.tsx
  src/app/ui/common/label.tsx
  src/app/ui/main/input-form.tsx
  src/app/ui/main/input-repository.tsx
  src/mocks/data/branches.json
Labels: ✨ feat, 🔍 review

#19 Feat: Report 페이지 UI 작업
  pnpm-lock.yaml
  src/app/report-view/page.tsx
  src/app/types/commit.ts
  src/app/ui/report-view/aside-area/aside-section.tsx
  src/app/ui/report-view/aside-area/commit-box.tsx
  src/app/ui/report-view/aside-area/commit-list.tsx
  src/app/ui/report-view/aside-area/requirement-list.tsx
  src/app/ui/report-view/header/header.tsx
  src/app/ui/report-view/main-area/commit/analysis-summary.tsx
  src/app/ui/report-view/main-area/commit/commit-section.tsx
  src/app/ui/report-view/main-area/commit/diagram-box.tsx
  src/app/ui/report-view/main-area/commit/key-changes.tsx
  src/app/ui/report-view/main-area/main-section.tsx
  src/app/ui/report-view/main-area/summary/summary-box.tsx
  src/mocks/data/report.json
Labels: ✨ feat, 🔍 review

#18 Feat: mermaid 적용
  package-lock.json
  package.json
  src/app/types/mermaid.ts
  src/app/ui/report-view/mermaid.tsx
  src/app/ui/report-view/useRenderMermaid.ts
  src/constants/error-messages.ts
  src/mocks/data/mermaid.json
Labels: ✨ feat

#21 Fix: 유효성 검증 규칙 일관화
  src/constants/error-messages.ts
  src/constants/validations.ts
  src/lib/validators/repository-url.ts
Labels: 🔨 fix
