Repository team-vaco-20/ssakssak-commit, pull requests merged in 2025-09, with the labels that each got.

#28 Feat: 로그인, 회원가입 페이지 UI 작업
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/app/ui/common/button.tsx
  src/app/ui/sign/auth-section.tsx
  src/app/ui/sign/header-section.tsx
Labels: ✨ feat

#34 Feat:Open AI API 분석 기능 구현
  package-lock.json
  package.json
  src/app/api/openai/route.ts
  src/app/types/commit.ts
  src/constants/error-messages.ts
  src/constants/open-ai.ts
  src/errors/bad-gateway-error.ts
  src/errors/index.ts
  src/errors/unprocessable-entity-error.ts
  src/infra/openai-api/helpers/create-input-blocks.ts
  src/infra/openai-api/helpers/response-check.ts
  src/infra/openai-api/instructions.ts
  src/infra/openai-api/openai-client.ts
  src/lib/logger.ts
  src/lib/validators/repository-url.ts
  src/lib/validators/structured-analysis-result.ts
  src/mocks/data/long-commit-result.json
  src/mocks/data/long-commit.json
  src/services/commit-analysis/analyze-commits.ts
  src/services/commit-analysis/helpers/chunk-commits-by-tokens.ts
  src/services/commit-analysis/helpers/extract-commit-summaries.ts
  src/services/commit-analysis/helpers/sort-merged-results.ts
Labels: 🔨 fix, ♻️ refactor, ✨ feat, 🔍 review

#40 Feat: SideBar 레이아웃 및 리포트 기록 관리
  src/app/(no-layout)/auth/error/page.tsx
  src/app/(no-layout)/loading/page.tsx
  src/app/(no-layout)/login/page.tsx
  src/app/(with-layout)/layout.tsx
  src/app/(with-layout)/page.tsx
  src/app/(with-layout)/report-view/[id]/page.tsx
  src/app/layout.tsx
  src/app/types/report-history.ts
  src/app/ui/common/Modal.tsx
  src/app/ui/common/input.tsx
  src/app/ui/layout/sections/nav/home-link.tsx
  src/app/ui/layout/sections/nav/nav-link.tsx
  src/app/ui/layout/sections/nav/nav-links.tsx
  src/app/ui/layout/sections/nav/sign-buttons.tsx
  src/app/ui/layout/sections/report-history/item.tsx
  src/app/ui/layout/sections/report-history/list.tsx
  src/app/ui/layout/sections/report-history/panel.tsx
  src/app/ui/layout/side-nav.tsx
  src/app/ui/main/report-form.tsx
  src/app/ui/main/repository-branch-selector.tsx
  src/app/ui/report-view/mermaid.tsx
  src/constants/error-messages.ts
  src/hooks/useRenderMermaid.ts
  src/hooks/useVerifiedContext.tsx
  src/lib/validators/report-fields.ts
  src/mocks/data/report-history-list.json
  src/stores/report-history/report-history-provider.tsx
Labels: ♻️ refactor, ✨ feat, 💄 design

#44 Feat: 프라이빗 리포지토리 연결
  src/app/(with-layout)/report-view/[id]/page.tsx
  src/app/types/analysis.ts
  src/app/types/commit.ts
  src/app/types/mock_commitInfo.ts
  src/app/types/next-auth.d.ts
  src/app/types/report.ts
  src/app/ui/layout/sections/nav/home-link.tsx
  src/app/ui/layout/sections/nav/nav-link.tsx
  src/app/ui/layout/sections/nav/sign-buttons.tsx
  src/app/ui/layout/sections/report-history/item.tsx
  src/app/ui/layout/sections/report-history/list.tsx
  src/app/ui/layout/sections/report-history/panel.tsx
  src/app/ui/main/repository-branch-selector.tsx
  src/infra/github-api/branches/get-branch-list.ts
  src/infra/github-api/commits/get-commit-details.ts
  src/infra/github-api/commits/get-commit-list.ts
  src/lib/auth/auth-options.ts
  src/lib/auth/callbacks/session.ts
  src/lib/validators/report-fields.ts
  src/services/commit-analysis/analyze-commits.ts
  src/services/commit-analysis/helpers/chunk-commits-by-tokens.ts
Labels: 🔨 fix, ♻️ refactor, ✨ feat, 🔍 review
